apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: petclinic
spec:
  source:
    git:
      ref: main
      uri: 'https://github.com/aaronjee/gmarket'
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: 'petclinic:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'java:latest'
        namespace: openshift
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
