apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: petclinic
spec:
  template:
    spec:
      containers:
      - name: petclinic
        image: image-registry.openshift-image-registry.svc:5000/gitops-dev/petclinic:latest
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
