apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  template:
    spec:
      containers:
      - name: petclinic
        image: image-registry.openshift-image-registry.svc:5000/gitops-dev/petclinic:dev-2021
