apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dev-petclinic
  namespace: gitops-dev
spec:
  source:
    git:
      ref: main
      uri: 'https://github.com/aaronjee/gmarket/petclinic'
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: 'dev-petclinic:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'java:latest'
        namespace: openshift
      env: []
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
