apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The application's http port.
  labels:
    application: petclinic
  name: petclinic
spec:
  selector:
    deploymentConfig: petclinic
  ports:
  - port: 8080
    targetPort: 8080
